version: '3'

services:
  bot:
    container_name: taalbot
    image: ${DOCKERHUB_USERNAME}/taalbot:${TAALBOT_VERSION}
    environment:
      TOKEN: ${TOKEN}
      PORT: ?? #or use:
    ports:
      - "81:80" # host:container
