name: Run Linting (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint with Pylint
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
