name: Deploy Bot (Experimental)

on:
  push:
    branches: [ experimental ]

jobs:
  deploy:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taalbot:experimental

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Transfer checked-put Code to Remote Server
      # TODO

      - name: Run docker-compose on Remote Server
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
          SCRIPT: |
            cd taalbot
            git pull https://github.com/HenningBuhl/Taalbot
            TAALBOT_VERSION=experimental
            docker-compose down
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/taalbot:experimental
            docker-compose up -d
